# Generated by Django 3.2.5 on 2021-08-01 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('rollno', models.BigIntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('batch_year', models.TextField()),
                ('address', models.TextField()),
                ('occupation', models.TextField()),
                ('company', models.TextField()),
                ('job_title', models.TextField()),
                ('job_location', models.TextField()),
                ('package', models.BigIntegerField()),
                ('skills', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('link', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('batch_year', models.TextField()),
                ('address', models.TextField()),
                ('skills', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_comment', models.DateField(default=datetime.date.today)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumni')),
            ],
        ),
    ]
